module.exports = [
  {
    lid: "LI-1000",
    name: "Test tube",
    quantity: 50,
    quality: "class a",
    price: "6000",
    batchCode: "DF-1000",
    supplier: "laboratory of zambales",
    contact: "091231554400",
    address: "iba",
    destination: "laboratory",
    description: "a cylindrical round-bottomed glass tube open at one end",
    userId: 2,
  },
  {
    lid: "LI-1001",
    name: "Beaker",
    quantity: 10,
    quality: "class a",
    price: "12000",
    batchCode: "DF-1001",
    supplier: "united lab",
    contact: "09123155441",
    address: "california",
    destination: "laboratory",
    description: "a cylindrical vessel, usually of glass, with a flat bottom",
    userId: 2,
  },
  {
    lid: "LI-1002",
    name: "Syringe",
    quantity: 2000,
    quality: "class a",
    price: "20000",
    batchCode: "DF-1002",
    supplier: "us medical center",
    contact: "09123155004",
    address: "san diego",
    destination: "laboratory",
    description:
      "a device used to inject fluids into or withdraw them from something",
    userId: 2,
  },
  {
    lid: "LI-1002",
    name: "Syringe",
    quantity: 200,
    quality: "class a",
    price: "2000",
    batchCode: "DF-1002",
    supplier: "us medical center",
    contact: "09123155004",
    address: "san diego",
    destination: "laboratory",
    description:
      "a device used to inject fluids into or withdraw them from something",
    userId: 2,
  },
];
