module.exports = [
  {
    mid: "MI-1000",
    name: "60 Watt Bulb",
    quantity: 50,
    quality: "class a",
    price: "600",
    batchCode: "MI-1000",
    supplier: "zambales light bulb inc",
    contact: "091231554400",
    address: "iba",
    destination: "maintenance",
    description:
      " light bulb, incandescent lamp or incandescent light globe is an electric light with a wire filament heated until it glows",
    userId: 2,
  },
  {
    mid: "MI-1001",
    name: "Electric Tape",
    quantity: 10,
    quality: "class b",
    price: "1200",
    batchCode: "MI-1001",
    supplier: "ph hardawares",
    contact: "09123155441",
    address: "manila",
    destination: "maintenance",
    description:
      "a type of pressure-sensitive tape used to insulate electrical wires and other materials that conduct electricity",
    userId: 2,
  },
  {
    mid: "MI-1004",
    name: "Electric Tape",
    quantity: 20,
    quality: "class b",
    price: "2400",
    batchCode: "MI-1004",
    supplier: "ph hardawares",
    contact: "09123155441",
    address: "manila",
    destination: "maintenance",
    description:
      "a type of pressure-sensitive tape used to insulate electrical wires and other materials that conduct electricity",
    userId: 2,
  },
  {
    mid: "MI-1002",
    name: "Pliers",
    quantity: 2,
    quality: "class a",
    price: "10000",
    batchCode: "MI-1002",
    supplier: "us medical center",
    contact: "09123155004",
    address: "olongapo",
    destination: "maintenance",
    description:
      "a device used to inject fluids into or withdraw them from something",
    userId: 2,
  },
];
