module.exports = [
  {
    oid: "oid-1000",
    name: "Pentel pen",
    quantity: 50,
    quality: "class b",
    price: "600",
    batchCode: "oid-1000",
    supplier: "office supplies inc",
    contact: "091231554400",
    address: "iba",
    destination: "office",
    description: "broad black pentel",
    userId: 2,
  },
  {
    oid: "oid-1001",
    name: "Ballpen",
    quantity: 10,
    quality: "class a",
    price: "12000",
    batchCode: "oid-1001",
    supplier: "office supplies inc",
    contact: "09123155441",
    address: "california",
    destination: "office",
    description: "1 box of hbw pens original",
    userId: 2,
  },
  {
    oid: "oid-1002",
    name: "Ruler",
    quantity: 20,
    quality: "class a",
    price: "2000",
    batchCode: "oid-1002",
    supplier: "office supplies inc",
    contact: "09123155004",
    address: "san diego",
    destination: "office",
    description: "a measuring tool",
    userId: 2,
  },
];
