module.exports = [
  {
    othid: "othid-1000",
    name: "Incense",
    quantity: 50,
    quality: "class a",
    price: "6000",
    batchCode: "DF-1000",
    supplier: "healing pharmacy ",
    contact: "091231554400",
    address: "iba",
    destination: "other",
    description: "use for calming ones mind",
    userId: 2,
  },
  {
    othid: "othid-1001",
    name: "Base Ball Bat",
    quantity: 1,
    quality: "class a",
    price: "1200",
    batchCode: "DF-1001",
    supplier: "united sports center",
    contact: "09123155441",
    address: "california",
    destination: "other",
    description: "a bat use for sports events",
    userId: 2,
  },
  {
    othid: "othid-1002",
    name: "Tractor Tires",
    quantity: 4,
    quality: "class a",
    price: "80000",
    batchCode: "othid-1002",
    supplier: "us tire center",
    contact: "09123155004",
    address: "san diego",
    destination: "other",
    description: "reserve tires for tractors rear tires",
    userId: 2,
  },
  {
    othid: "othid-1003",
    name: "Tractor Tires",
    quantity: 5,
    quality: "class a",
    price: "100000",
    batchCode: "othid-1003",
    supplier: "us tire center",
    contact: "09123155004",
    address: "san diego",
    destination: "other",
    description: "reserve tires for tractors rear tires",
    userId: 2,
  },
];
